{% set name = "idna-ssl" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower|replace("-","_") }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a933e3bb13da54383f9e8f35dc4f9cb9eb9b3b78c6b36f311254d6d0d92c6c7c

build:
  number: 1001
  skip: True  # [py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - idna >=2

test:
  imports:
    - idna_ssl

about:
  home: https://github.com/aio-libs/idna-ssl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Patch ssl.match_hostname for Unicode(idna) domains support'

  dev_url: https://github.com/aio-libs/idna-ssl

extra:
  recipe-maintainers:
    - sodre
