travis:
  secure:
    BINSTAR_TOKEN: NyvvqSxqASseoC7lBZebJovoQbPZGfjDrwk5WQa6m0A952SZz7VNgBp6cnKxeYphyGPwqGanTf9bs+3MZh4trwf0x4iDRDCvJtSUQZWKsW32CJN0JIMQnaxFYAkFDPlyxesFVnVF/1VwepXdrCcNGQuEod0Jy1jERY55gn0SKOC4ALVv5u/2+db5Q15tFXVW4y5riPDmCncWARqM/TRlp1MXXt3vmbXg5bHyquluFq//4b35r28Bwz08kVSA/RptNA1FQnG7wvymeHsZqhZRmzWWsICXztmJGNOuX1ElnpZcMxSwwdKzcyUG4y9/m0LtgEQuVxyw/J+gQ4CnJUqWYg8gxFQ/WSpMmhtrqqnn8yNc0qTM3N/gE/SaosuQyKWftHWLsJ648StZYZZBENDj0a7XnOz4Zwos1tBr5Y1454guIjQCmfpdXcviPRpRQSJDswyVsJQRtX24le2q+Defu/TENhG8s/cePF4+Qaq5jfzF0Dyxh/8hkJciOjpE+rhkSrL5ycXF/yYfC7ds921XLzdcmfAbOzPekOni4iLFEUkd8RQKPBjDmYSc7z12qYmN9N6STZVlptPRKTou/eeISENxQQz9SF3cbFaUV01lyqOGKGfbPvO2U73/wf6g9Y+l0y0mtETICwX4oGMrrzJ1AEqAOv7MUZw5sR/02ZyYNmg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
